/**
 * POST /api/applications/[id]/revise/[stepId]
 *
 * Lets a student go back and edit a previously completed step. Marks that
 * step as pending again, clears its response, and deletes every subsequent
 * step (those were generated by GLM based on the now-stale answer — they
 * need to be re-emitted from scratch when the student re-submits).
 *
 * Only allowed while the application is still in draft. Once submitted,
 * the immutable record is what the coordinator reviewed.
 */

import { NextRequest } from "next/server";
import { requireUser } from "@/lib/auth/guards";
import { getServiceSupabase } from "@/lib/supabase/server";
import { apiError, apiSuccess } from "@/lib/utils/responses";

export async function POST(_req: NextRequest, ctx: { params: Promise<{ id: string; stepId: string }> }) {
  const user = await requireUser();
  if (!user) return apiError("Not authenticated", 401);

  const { id: applicationId, stepId } = await ctx.params;
  const sb = getServiceSupabase();

  const { data: app } = await sb
    .from("applications")
    .select("id, user_id, status")
    .eq("id", applicationId)
    .single();
  if (!app) return apiError("Application not found", 404);
  if (app.user_id !== user.id) return apiError("Forbidden", 403);
  // Allow revise on draft AND more_info_requested. After a coordinator
  // requests more info the student gets new pending steps; they should
  // still be able to revise their original answers if they realise they
  // got something wrong.
  if (app.status !== "draft" && app.status !== "more_info_requested") {
    return apiError(`Cannot revise — application is ${app.status}`, 409);
  }

  const { data: step } = await sb
    .from("application_steps")
    .select("id, ordinal, status, application_id")
    .eq("id", stepId)
    .single();
  if (!step) return apiError("Step not found", 404);
  if (step.application_id !== applicationId) return apiError("Step belongs to a different application", 400);
  if (step.status !== "completed") {
    return apiError(`Cannot revise — step status is ${step.status}`, 409);
  }

  // Delete every step after this one (they were generated based on the
  // about-to-change answer, so they're stale).
  const { error: delErr } = await sb
    .from("application_steps")
    .delete()
    .eq("application_id", applicationId)
    .gt("ordinal", step.ordinal);
  if (delErr) return apiError(`Failed to clear later steps: ${delErr.message}`, 500);

  // Reset the target step to pending so the student can edit and re-submit.
  const { error: updErr } = await sb
    .from("application_steps")
    .update({
      status: "pending",
      response_data: null,
      completed_at: null,
    })
    .eq("id", stepId);
  if (updErr) return apiError(`Failed to reset step: ${updErr.message}`, 500);

  // Recompute the running count of completed steps and refresh the
  // application's progress counter. Without this the Portal tile still
  // showed the pre-revise number until the student completed another step.
  const { count: completedCount } = await sb
    .from("application_steps")
    .select("id", { count: "exact", head: true })
    .eq("application_id", applicationId)
    .eq("status", "completed");

  // Touch the application so realtime subscribers refresh + sync progress.
  await sb
    .from("applications")
    .update({
      updated_at: new Date().toISOString(),
      ...(typeof completedCount === "number"
        ? { progress_current_step: completedCount }
        : {}),
    })
    .eq("id", applicationId);

  return apiSuccess({
    revised: true,
    step_id: stepId,
    deleted_subsequent_count: 0, // we don't count for now; client refresh shows truth
  });
}
